name: FMI CAP profile distribution

on: push

jobs:
  create_profile_distribution:
    name: Create profile distribution
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        id: get_branch
        run: echo ::set-output name=BRANCH::${GITHUB_REF##*/}
      - name: Create output directory
        run: mkdir -p output/${{ steps.get_branch.outputs.BRANCH }}
      - name: Copy Markdown document
        run: cp fmi-cap-profile.md output/${{ steps.get_branch.outputs.BRANCH }}/fmi-cap-profile-${{ steps.get_branch.outputs.BRANCH }}.md
      - name: Convert to HTML document
        uses: docker://pandoc/latex:2.9.2
        with:
          args: "--from=gfm --to=html --standalone --self-contained --css=template/style.css -o output/${{ steps.get_branch.outputs.BRANCH }}/fmi-cap-profile-${{ steps.get_branch.outputs.BRANCH }}.html fmi-cap-profile.md"
      - name: Package
        uses: actions/upload-artifact@master
        with:
          name: fmi-cap-profile-${{ steps.get_branch.outputs.BRANCH }}
          path: output
